---
title: "Main components of an R-package"
author: 
date: "September 23, 2019"
output: revealjs::revealjs_presentation
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Why an R package

https://adv-r.hadley.nz/functions.html
https://r4ds.had.co.nz/functions.html#introduction-12

## Before starting

Does a package of that kind already exist?

What is different about yours? What is the usecase and unique feature of yours?

Are there any conventions/standards you could adapt? Is there a framework into which you want/should embed your package?

How shall it be called? (good luck with that...)

## Starting

Set up an R-Studio Project (highly recommended): `create_package()`

check out `Alt + shift + K` 

## Package structure I

`R/` 

`NAMESPACE`

`DIRECTORY`

## Package structure II



package from a creators point of view/on github, with all the possible directories and files; perhaps simply use a couple of screenshots

## What is a function?

functions, like variables are objects in R

comprises a script and summarises a couple of related usecases that can be acccessed with arguments.

thus, functions are an interface between a certain algorithm and the outside environment (humnans, other software)

## What is a namespace?

this is an important, yet perhaps confusing topic at first

it is a wraper around the names of your packages' functions, so to speak

the namespace informs the R ecosystem about which functions your package provides (*exports*) and which functions it utilizes (*imports*)

it helps to avoid conflicts, in case functions names are or become duplicated

## Package description


